import java.io.IOException;

/**
 *
 * @author Chase Franse
 */
public class LeoLinuxApplicationSelector extends javax.swing.JFrame {

    /**
     * Creates new form LeoLinuxApplicationSelector
     */
    public LeoLinuxApplicationSelector() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        header = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LeoLinux Application Selector");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        
        header.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("LeoLinux Custom Applications");
        header.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Set Time");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTimeBtnClick(evt);
            }
        });

        jButton2.setText("App Store");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appStoreBtnClick(evt);
            }
        });

        jButton3.setText("Delete User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnClick(evt);
            }
        });

        jButton4.setText("Bracket Checker");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracketCheckerBtnClick(evt);
            }
        });

        jButton5.setText("New User");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserBtnClick(evt);
            }
        });

        jButton6.setText("Samba Set-Up");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sambaSetupBtnClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void appStoreBtnClick(java.awt.event.ActionEvent evt) {                                  
        // TODO add your handling code here:
    	//JOptionPane.showMessageDialog(rootPane, "App Store Btn Clicked!");
    	
        try {
        	//Process processStart = process.start();
        	Process process = Runtime.getRuntime().exec("java -jar /.leolinuxcustom/programs/LeoLinuxJFramev1.jar");
		} catch (IOException e) {
			e.printStackTrace();
		}
        System.exit(0);
    }                                 

    private void setTimeBtnClick(java.awt.event.ActionEvent evt) {                                 
        // TODO add your handling code here:
    	//JOptionPane.showMessageDialog(rootPane, "Set Time Btn Clicked!");
    	
    	try {
    		Process process = Runtime.getRuntime().exec("sudo xfce4-terminal -e /.leolinuxcustom/programs/LOCALclockUpdate.sh");
		} catch (IOException e) {
			e.printStackTrace();
		}
    	System.exit(0);
    }                                

    private void bracketCheckerBtnClick(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	//JOptionPane.showMessageDialog(rootPane, "Bracket Checker Btn Clicked!");

    	try {
    		Process process = Runtime.getRuntime().exec("java -jar /.leolinuxcustom/programs/Bracket_Checker-5.7.jar");
		} catch (IOException e) {
			e.printStackTrace();
		}
        System.exit(0);
    }                                       

    private void newUserBtnClick(java.awt.event.ActionEvent evt) {                                 
        // TODO add your handling code here:
    	//JOptionPane.showMessageDialog(rootPane, "New User Btn Clicked!");

        try {
        	Process process = Runtime.getRuntime().exec("sudo xfce4-terminal -e /.leolinuxcustom/programs/newUser.sh");
		} catch (IOException e) {
			e.printStackTrace();
		}
        System.exit(0);
    }                                

    private void deleteUserBtnClick(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    	//JOptionPane.showMessageDialog(rootPane, "Delete User Btn Clicked!");

        try {
        	Process process = Runtime.getRuntime().exec("sudo xfce4-terminal -e /.leolinuxcustom/programs/delUser.sh");
		} catch (IOException e) {
			e.printStackTrace();
		}
        System.exit(0);
    }                                

    private void sambaSetupBtnClick(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    	try {
    		Process process = Runtime.getRuntime().exec("sudo xfce4-terminal -e /.leolinuxcustom/programs/sambaInstaller.sh");
		} catch (IOException e) {
			e.printStackTrace();
		}
    	System.exit(0);
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeoLinuxApplicationSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeoLinuxApplicationSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeoLinuxApplicationSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeoLinuxApplicationSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeoLinuxApplicationSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration                   
}
